# Generated by Django 5.2.16 on 2026-09-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_net_amount_invoice_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_label',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
