# Generated by Django 5.2.16 on 2026-09-20 15:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_backfill_opening_stock'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cost_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', 0), _connector='OR'), name='sale_item_unit_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('cost_subtotal__isnull', True), ('cost_subtotal__gte', 0), _connector='OR'), name='sale_item_cost_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cost_subtotal__isnull', True), ('unit_cost__isnull', True)), models.Q(('cost_subtotal__isnull', False), ('unit_cost__isnull', False)), _connector='OR'), name='sale_item_cost_snapshot_complete'),
        ),
    ]
