# Generated by Django 5.2.16 on 2026-09-25 19:42

import django.core.validators
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_net_amount(apps, schema_editor):
    """Sales predating tax were untaxed, so their total was already the net.

    This has to run before the total = net + tax constraint is added, or every
    existing Sale fails it with net_amount still at the column default of 0.
    """
    Sale = apps.get_model("sales", "Sale")
    Sale.objects.update(net_amount=models.F("total_amount"))


def unbackfill_net_amount(apps, schema_editor):
    """No-op: the column is dropped when this migration is reversed."""


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0002_backfill_opening_stock'),
        ('products', '0001_initial'),
        ('sales', '0002_saleitem_cost_subtotal_saleitem_unit_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.RunPython(backfill_net_amount, unbackfill_net_amount),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='sale_net_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='sale_tax_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0)), name='sale_tax_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(models.F('net_amount'), '+', models.F('tax_amount')))), name='sale_total_is_net_plus_tax'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='sale_item_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('unit_price'), '*', models.F('quantity')), '-', models.F('discount_amount')))), name='sale_item_subtotal_matches_line_maths'),
        ),
    ]
