# Generated by Django 5.2.16 on 2026-09-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_net_amount_sale_tax_amount_sale_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tax_label',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
