# Generated by Django 5.2.16 on 2026-09-26 15:18

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0004_sale_tax_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_tendered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_given',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('EWALLET', 'E-wallet'), ('TRANSFER', 'Bank transfer')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_tendered__isnull', True), ('change_given__isnull', True)), models.Q(('amount_tendered__isnull', False), ('change_given__isnull', False)), _connector='OR'), name='sale_cash_fields_recorded_together'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('change_given__isnull', True), ('change_given', django.db.models.expressions.CombinedExpression(models.F('amount_tendered'), '-', models.F('total_amount'))), _connector='OR'), name='sale_change_is_tendered_less_total'),
        ),
        migrations.AddField(
            model_name='salereversal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_reversals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salereversal',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='sales.sale'),
        ),
    ]
