# Generated by Django 5.2.16 on 2026-08-13 06:55

import django.core.validators
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'sku'],
                'constraints': [models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='product_selling_price_nonnegative'), models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='product_cost_price_nonnegative'), models.CheckConstraint(condition=models.Q(('current_stock__gte', 0)), name='product_current_stock_nonnegative'), models.CheckConstraint(condition=models.Q(('low_stock_threshold__gte', 0)), name='product_low_stock_threshold_nonnegative'), models.CheckConstraint(condition=models.Q(('sku', django.db.models.functions.text.Upper('sku'))), name='product_sku_uppercase')],
            },
        ),
    ]
